import { Breadcrumb } from "@/components/breadcrumb"
import { Heading } from "@/components/heading"

export default function PlatformPage() {
  return (
    <div className="space-y-6">
      <Breadcrumb
        items={[
          { title: "Docs", href: "/docs" },
          { title: "Dobprotocol Platform", href: "/docs/platform" }
        ]}
      />
      
      <Heading level={1}>Dobprotocol Platform</Heading>
      
      <div className="prose max-w-none">
        <p className="text-lg text-gray-300">
          In an era of rapid financial innovation, real-world asset tokenization (RWA) has emerged as a transformative force, opening up new realms of investment and asset management.
        </p>

        <p>
          At the heart of this revolution is Dobprotocol, an open source project that is redefining the way we think about the distribution and management of RWA.
        </p>

        <p>
          Harnessing the power of blockchain technology, Dobprotocol enables businesses and individuals alike to easily tokenize and distribute the benefits generated by various assets, from real estate and natural resources to a myriad of tangible goods.
        </p>

        <p>
          With an ambitious projection, Dobprotocol aims to capture 0.25% of the RWA market, representing approximately $250 million in operational assets.
        </p>

        <p>
          One of Dobprotocol&apos;s defining characteristics is its multichain approach. Unlike many protocols tied to a single blockchain, Dobprotocol is designed to be agnostic.
        </p>

        <p>
          This flexibility ensures that Dobprotocol can cater to a diverse user base, ensuring that everyone can benefit from its innovative solutions.
        </p>

        <Heading level={2}>Transforming Real World Asset (RWA) management</Heading>

        <p>
          At Dobprotocol, we&apos;re revolutionizing with groundbreaking technologies like Trusted Execution Environments (TEEs) and Zero-Knowledge Proofs (ZKP). Here&apos;s how we&apos;re revolutionizing decentralized asset flow across industries:
        </p>

        <Heading level={3}>EV-Chargers as Real World Assets</Heading>

        <p>
          Our EV chargers are equipped with TEEs to generate raw operational reports with tamper-proof data integrity. This ensures transparency and sets the foundation for automated revenue sharing.
        </p>

        <Heading level={3}>DBS Accountability System</Heading>

        <p>
          Using TEEs, our accountability system processes raw reports into reliable accounting logs. This secures communication between OCPP servers and guarantees trustworthy data for operations.
        </p>

        <Heading level={3}>DOBI Fuzzy AI Agent</Heading>

        <p>
          Our DOBI agent tackles uncertainty in accounting data with Fuzzy AI, generating Zero-Knowledge Proofs (ZKP) for privacy and data integrity. This ensures the highest level of security without exposing sensitive information.
        </p>

        <Heading level={3}>Smart Contract Pool</Heading>

        <p>
          Funds flow directly into our smart contract pool, where ZKPs verify their origin and accuracy without revealing confidential details. This creates a seamless and trustless link between EV charger operations and token holders.
        </p>

        <Heading level={3}>Automated Revenue Distribution</Heading>

        <p>
          Finally, funds are transparently and automatically distributed to token holders, ensuring that the benefits of EV-charger operations are shared among all stakeholders in a secure and efficient manner.
        </p>

        <Heading level={2}>Ehive: electric mobility with Blockchain</Heading>

        <div className="my-8 py-4 bg-gray-800 text-center text-gray-400 rounded-lg">
          [Ehive electric mobility with Blockchain - Image]
        </div>

        <p>
          Ehive is a pioneering project revolutionizing the electric mobility sector by integrating blockchain technology into its business model. Its primary goal is to make sustainable technology more accessible while offering profitable investment opportunities. With a unified platform, Ehive simplifies the installation, management, and real-time monitoring of EV charging stations, ensuring efficiency and adaptability in its operations.
        </p>

        <p>
          Through Dobprotocol, you&apos;ll be able to invest in Ehive securely, automatically, and transparently. This project is the first in the Dobprotocol ecosystem to tokenize electric charging infrastructure, allowing investors to participate in the growth of a sustainable business while earning direct returns. Profit distributions are carried out automatically, ensuring a seamless and trustworthy experience.
        </p>

        <p>
          By combining Ehive&apos;s innovation with Dobprotocol&apos;s technology, we are taking a bold step toward a future where investments in Real World Assets are accessible, efficient, and sustainable. Together, we redefine ownership and democratize investment opportunities in electric mobility.
        </p>
      </div>
    </div>
  )
}
