import { Heading } from "@/components/heading"
import { Breadcrumb } from "@/components/breadcrumb"
import Link from "next/link"

export default function DobiEhivePage() {
  return (
    <div className="space-y-6">
      <Breadcrumb items={[
        { title: "Docs", href: "/docs" },
        { title: "$DOBI", href: "/docs/dobi" },
        { title: "Ehive", href: "/docs/dobi/ehive" }
      ]} />
      
      <Heading level={1}>DOBI & Ehive</Heading>
      
      <div className="prose max-w-none">
        <p className="text-lg text-gray-300">
          DOBI&apos;s capabilities are designed to create a secure, efficient, and automated framework for projects like Ehive, 
          a pioneering initiative focused on electric mobility. This synergy between DOBI and Ehive will revolutionize 
          the way blockchain technology intersects with sustainable investments.
        </p>

        <p>
          Ehive is a forward-thinking project that tokenizes electric vehicle (EV) charging infrastructure, enabling 
          investors to participate in the growing EV industry through blockchain. The integration of DOBI will elevate 
          this model by validating off-chain data, ensuring that each transaction within Ehive&apos;s ecosystem is reliable 
          and accurate.
        </p>

        <Heading level={2}>DOBI: Agent & Oracle</Heading>
        
        <p>
          One of DOBI&apos;s core functionalities is its ability to act as an oracle, validating off-chain data and bringing 
          it onto the blockchain for use in profit pools. In Ehive&apos;s case, DOBI will oversee data generated by EV 
          charging stations, such as:
        </p>
        
        <ul>
          <li>Energy consumption</li>
          <li>Transaction volumes</li>
          <li>Maintenance needs</li>
        </ul>

        <p>
          This ensures that all information used to distribute profits or approve transactions is trustworthy, fostering 
          confidence among investors. The future integration of DOBI into Ehive marks a new era for decentralized asset management.
        </p>

        <div className="p-4 bg-gray-800 rounded-lg my-6">
          <p className="text-gray-300 italic">
            <strong>AI-driven automation with blockchain technology:</strong> Dobprotocol and Ehive are setting a precedent 
            for how RWAs (Real World Assets) can be managed transparently and effectively. This collaboration highlights the 
            potential for decentralized autonomous machines (DAMs) to redefine ownership and investment in sustainable industries.
          </p>
        </div>

        <Heading level={2}>Key Benefits</Heading>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-6">
          <div className="p-4 bg-gray-800 rounded-lg">
            <h3 className="text-xl font-bold mb-2">Secure Validation</h3>
            <p>DOBI provides trustless validation of real-world EV charging data, ensuring accuracy in revenue distribution.</p>
          </div>
          
          <div className="p-4 bg-gray-800 rounded-lg">
            <h3 className="text-xl font-bold mb-2">Automated Operations</h3>
            <p>AI-driven oversight reduces operational costs and human error in managing EV infrastructure.</p>
          </div>
          
          <div className="p-4 bg-gray-800 rounded-lg">
            <h3 className="text-xl font-bold mb-2">Transparent Investment</h3>
            <p>Blockchain integration provides immutable records of all transactions and revenue flows.</p>
          </div>
          
          <div className="p-4 bg-gray-800 rounded-lg">
            <h3 className="text-xl font-bold mb-2">Sustainable Growth</h3>
            <p>The partnership promotes expansion of green energy infrastructure through decentralized funding.</p>
          </div>
        </div>

        <Heading level={2}>Future Developments</Heading>
        
        <p>
          The DOBI and Ehive collaboration is in its early stages, with several exciting developments on the horizon:
        </p>
        
        <ul>
          <li><strong>Advanced Data Analytics:</strong> Implementation of machine learning to optimize charging station performance and usage</li>
          <li><strong>Expanded Network:</strong> Integration with additional EV infrastructure beyond charging stations</li>
          <li><strong>Enhanced Tokenization:</strong> Improved mechanisms for fractional ownership of sustainable energy assets</li>
          <li><strong>Cross-Chain Compatibility:</strong> Support for multiple blockchain networks to increase accessibility</li>
        </ul>

        <p className="text-lg font-semibold mt-6">
          Stay tuned for updates as this groundbreaking partnership continues to evolve. 
          <Link href="/docs/dobi" className="ml-2 text-blue-400 hover:text-blue-300">
            Learn more about DOBI
          </Link>
        </p>
      </div>
    </div>
  )
} 